using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZwiftFitFileDownloaderConsoleApp
{
    internal class Constants
    {
        public const string AccessToken = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJPLUVjXzJJNjg5bW9peGJIZzFfNDZDVFlGeEdZMDViaDluYm5Mcjl0RzY4In0.eyJleHAiOjE2NTQxNjE1MTYsImlhdCI6MTY1NDEzOTkxNiwianRpIjoiYzhjNzMxODEtYTczZi00NzEyLWEwYzctMjg0YWVkYjgyNTVlIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmUuendpZnQuY29tL2F1dGgvcmVhbG1zL3p3aWZ0IiwiYXVkIjpbImVtYWlsLXByZWZzLXNlcnZpY2UiLCJteS16d2lmdCIsInNzby1nYXRld2F5Iiwic3Vic2NyaXB0aW9uLXNlcnZpY2UiLCJHYW1lX0xhdW5jaGVyIiwiWndpZnQgWmVuZGVzayIsIlp3aWZ0IFJFU1QgQVBJIC0tIHByb2R1Y3Rpb24iLCJad2lmdCBSZWxheSBSRVNUIEFQSSAtL…ZlcnJlZF91c2VybmFtZSI6ImRpZWdvLnNjaGxlaXMyOUBnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiRGllZ28iLCJmYW1pbHlfbmFtZSI6IlNjaGxlaXMiLCJlbWFpbCI6ImRpZWdvLnNjaGxlaXMyOUBnbWFpbC5jb20ifQ.daMBjKw7j7OJrDVMGZn6ivVDW3ihvnfXHmni4UAAvwvXtTPVAhbxiFJDCNEC7FhBgoQcOKEWUfNZT5H15PeWplFIzhoub4sHeSOooTMwI0ee9v8QJGQS7h04qMjmtLddXL8Roc_ceElQjG-p58pBs_8S2z8jaqnFEm47D7n9XRKwGc0EnadHwO5rNcE6bu8uT-cV24dSREWq-gwq47NQnOfsBNzBK7yiCUwmp8aKmRDUY1XTHjbiJPf_sVgWetRBUbsIaudyYZ2-sxE6b96Qz8kuz44uFfqNc2mLKsRbFWxzSYq6NR0nu5lApYdWskijDfL6u7_gqzMsYP2Z7_UtXw";
    }
}
