// See https://aka.ms/new-console-template for more information
using System.Globalization;
using ZwiftFitFileDownloaderConsoleApp.Classes;

Console.WriteLine("Hello, World!");

ZwiftHelper zh = new ZwiftHelper();

Console.WriteLine("Please enter your Zwift access token.");
//var token = Console.ReadLine();
var token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJPLUVjXzJJNjg5bW9peGJIZzFfNDZDVFlGeEdZMDViaDluYm5Mcjl0RzY4In0.eyJleHAiOjE2NTQxNjE1MTYsImlhdCI6MTY1NDEzOTkxNiwianRpIjoiYzhjNzMxODEtYTczZi00NzEyLWEwYzctMjg0YWVkYjgyNTVlIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmUuendpZnQuY29tL2F1dGgvcmVhbG1zL3p3aWZ0IiwiYXVkIjpbImVtYWlsLXByZWZzLXNlcnZpY2UiLCJteS16d2lmdCIsInNzby1nYXRld2F5Iiwic3Vic2NyaXB0aW9uLXNlcnZpY2UiLCJHYW1lX0xhdW5jaGVyIiwiWndpZnQgWmVuZGVzayIsIlp3aWZ0IFJFU1QgQVBJIC0tIHByb2R1Y3Rpb24iLCJad2lmdCBSZWxheSBSRVNUIEFQSSAtLSBwcm9kdWN0aW9uIiwiZWNvbS1zZXJ2ZXIiLCJhY2NvdW50Il0sInN1YiI6IjlmYTg0Zjk1LTc2ZTItNDE4YS1hYjI2LWMyYzVkOWQ5ZGI1YiIsInR5cCI6IkJlYXJlciIsImF6cCI6Inp3aWZ0LXB1YmxpYyIsInNlc3Npb25fc3RhdGUiOiIxZWI2YWEyMS1mMmNlLTQ3M2ItYTM3My02YjA2YjA0MWRkMjIiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vd3d3Lnp3aWZ0LmNvbSIsImh0dHBzOi8vd2ViLnByZC1kbXouendpZnQuY29tIiwiaHR0cHM6Ly96d2lmdC5jb20iXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInRyaWFsLXN1YnNjcmliZXIiLCJiZXRhLXRlc3RlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImVtYWlsLXByZWZzLXNlcnZpY2UiOnsicm9sZXMiOlsiYXV0aGVudGljYXRlZC11c2VyIl19LCJteS16d2lmdCI6eyJyb2xlcyI6WyJhdXRoZW50aWNhdGVkLXVzZXIiXX0sInNzby1nYXRld2F5Ijp7InJvbGVzIjpbImF1dGhlbnRpY2F0ZWQtdXNlciJdfSwic3Vic2NyaXB0aW9uLXNlcnZpY2UiOnsicm9sZXMiOlsiYXV0aGVudGljYXRlZC11c2VyIl19LCJHYW1lX0xhdW5jaGVyIjp7InJvbGVzIjpbImF1dGhlbnRpY2F0ZWQtdXNlciJdfSwiWndpZnQgWmVuZGVzayI6eyJyb2xlcyI6WyJhdXRoZW50aWNhdGVkLXVzZXIiXX0sIlp3aWZ0IFJFU1QgQVBJIC0tIHByb2R1Y3Rpb24iOnsicm9sZXMiOlsiYXV0aG9yaXplZC1wbGF5ZXIiLCJhdXRoZW50aWNhdGVkLXVzZXIiXX0sIlp3aWZ0IFJlbGF5IFJFU1QgQVBJIC0tIHByb2R1Y3Rpb24iOnsicm9sZXMiOlsiYXV0aG9yaXplZC1wbGF5ZXIiXX0sImVjb20tc2VydmVyIjp7InJvbGVzIjpbImF1dGhlbnRpY2F0ZWQtdXNlciJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiIiLCJuYW1lIjoiRGllZ28gU2NobGVpcyIsInByZWZlcnJlZF91c2VybmFtZSI6ImRpZWdvLnNjaGxlaXMyOUBnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiRGllZ28iLCJmYW1pbHlfbmFtZSI6IlNjaGxlaXMiLCJlbWFpbCI6ImRpZWdvLnNjaGxlaXMyOUBnbWFpbC5jb20ifQ.daMBjKw7j7OJrDVMGZn6ivVDW3ihvnfXHmni4UAAvwvXtTPVAhbxiFJDCNEC7FhBgoQcOKEWUfNZT5H15PeWplFIzhoub4sHeSOooTMwI0ee9v8QJGQS7h04qMjmtLddXL8Roc_ceElQjG-p58pBs_8S2z8jaqnFEm47D7n9XRKwGc0EnadHwO5rNcE6bu8uT-cV24dSREWq-gwq47NQnOfsBNzBK7yiCUwmp8aKmRDUY1XTHjbiJPf_sVgWetRBUbsIaudyYZ2-sxE6b96Qz8kuz44uFfqNc2mLKsRbFWxzSYq6NR0nu5lApYdWskijDfL6u7_gqzMsYP2Z7_UtXw";

Console.WriteLine("Please enter your Zwift user ID.");
//var userId = Console.ReadLine();
var userId = "4549600";

Console.WriteLine("Please enter your first zwift activity");
//var userId = Console.ReadLine();
var firstActivityDate = DateTime.ParseExact(Console.ReadLine(), "dd-MM-yyyy", CultureInfo.InvariantCulture);

var activities = zh.GetActivitiesForUser(token, userId, firstActivityDate);
activities.OrderByDescending(a => a.ActivityStartDate).ToList();

Console.WriteLine("Where should I put the fit files?");
var filePath = Console.ReadLine();

foreach (var activity in activities)
{

    zh.DownloadActivityFitFile(filePath, activity);
}
